### ISSUE TITLE
How do I fix Player Count issue?

### ISSUE THREAD

**Issue by VaibhavS-17** [AidenCooper/DiscordStatusBot#1]
Player count not showing please help.
![Screenshot_2024-06-09-19-31-08-10_572064f74bd5f9fa804b05334aa4f912](https://github.com/AidenCooper/DiscordStatusBot/assets/83623520/f32e7dc0-2f5a-4f03-91b0-0e9204ff4003)

**Comment by aidencooper** [comment]
You need to install PlaceholderAPI onto your server and install the Server expansion using /papi ecloud download Server

**Comment by VaibhavS-17** [comment]
Thank you so much its fixed now!
